#!/usr/bin/env python3
"""Generate docs/SKILLS_INVENTORY.md from SKILL.md files."""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sovereign_skills.core.skill_loader import SovereignSkillLoader

OUT = ROOT / "docs" / "SKILLS_INVENTORY.md"


def main() -> None:
    loader = SovereignSkillLoader()
    lines = [
        "# SovereignSkills Inventory",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} · **Count:** {len(loader.loaded_skills)}",
        "",
        "| Skill | Triggers | Description |",
        "|-------|----------|-------------|",
    ]
    for name in loader.list_skills():
        s = loader.loaded_skills[name]
        triggers = ", ".join(s.trigger_keywords[:6])
        if len(s.trigger_keywords) > 6:
            triggers += "…"
        desc = s.description.replace("|", "/")[:80]
        lines.append(f"| `{name}` | {triggers} | {desc} |")

    lines.extend([
        "",
        "---",
        "*Auto-generated by `scripts/generate_skills_inventory.py` — do not edit manually.*",
    ])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"✅ Wrote {OUT}")


if __name__ == "__main__":
    main()
